apiVersion: v1
kind: Service
metadata:
  name: authenticator
spec:
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 30001
      port: 8001
      targetPort: 8001
  selector:
    app: auth